apiVersion: v1
kind: PersistentVolume
metadata:
  name: clash
  labels:
    app.kubernetes.io/name: clash
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: clash-storage
  volumeMode: Filesystem
  local:
    path: /srv/clash
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud-server
