apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clash-home
  namespace: default
  labels:
    app.kubernetes.io/name: clash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: clash-storage
  volumeMode: Filesystem
