apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clash-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: clash
    namespace: default
roleRef:
  kind: Role
  name: clash-role
  apiGroup: rbac.authorization.k8s.io
