apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-template-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: kubernetes-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kubernetes-template-storage
  volumeMode: Filesystem
