apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-template-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kubernetes-template
    namespace: default
roleRef:
  kind: Role
  name: kubernetes-template-role
  apiGroup: rbac.authorization.k8s.io
