apiVersion: v1
kind: Service
metadata:
  name: kubernetes-template
  namespace: default
  labels:
    app: kubernetes-template
spec:
  type: NodePort
  selector:
    app: kubernetes-template
  ports:
    - name: http
      port: 80
      targetPort: 80
#     nodePort: 29880
