apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer
  labels:
    app.kubernetes.io/name: homer
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: homer-storage
  volumeMode: Filesystem
  local:
    path: /srv/homer
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud-server
