apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: default
  labels:
    app: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: api
      port: 8081
      targetPort: 8081
      nodePort: 8081
    - name: oci
      port: 5000
      targetPort: 5000
#     nodePort: 5000
