apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-ce
  labels:
    app.kubernetes.io/name: gitlab-ce
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-ce-storage
  volumeMode: Filesystem
  local:
    path: /srv/gitlab-ce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud-server
