apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-ce-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: gitlab-ce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gitlab-ce-storage
  volumeMode: Filesystem
