apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-ce-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: gitlab-ce
    namespace: default
roleRef:
  kind: Role
  name: gitlab-ce-role
  apiGroup: rbac.authorization.k8s.io
