apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce
  namespace: default
  labels:
    app: gitlab-ce
spec:
  type: NodePort
  selector:
    app: gitlab-ce
  ports:
    - name: http
      port: 28080
      targetPort: 28080
      nodePort: 28080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 28443
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 22222
