apiVersion: v1
kind: PersistentVolume
metadata:
  name: zentao
  labels:
    app.kubernetes.io/name: zentao
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: zentao-storage
  volumeMode: Filesystem
  local:
    path: /srv/zentao
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cloud-server
