apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zentao-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: zentao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zentao-storage
  volumeMode: Filesystem
