apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zentao-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: zentao
    namespace: default
roleRef:
  kind: Role
  name: zentao-role
  apiGroup: rbac.authorization.k8s.io
