apiVersion: v1
kind: Service
metadata:
  name: zentao
  namespace: default
  labels:
    app: zentao
spec:
  type: NodePort
  selector:
    app: zentao
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30808
