apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mysql
    namespace: default
roleRef:
  kind: Role
  name: mysql-role
  apiGroup: rbac.authorization.k8s.io
