apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jellyfin-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jellyfin
    namespace: default
roleRef:
  kind: ClusterRole
  name: jellyfin-cluster-role
  apiGroup: rbac.authorization.k8s.io
