apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: jellyfin
    namespace: default
roleRef:
  kind: Role
  name: jellyfin-role
  apiGroup: rbac.authorization.k8s.io
