apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: gitlab-runner
  name: gitlab-runner
  namespace: default
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gitlab-runner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      serviceAccountName: gitlab-runner
#     hostNetwork: true
      terminationGracePeriodSeconds: 30

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      volumes:
        - name: gitlab-runner-config
          configMap:
            name: gitlab-runner-config
#       - name: gitlab-runner-pvc
#         persistentVolumeClaim:
#           claimName: gitlab-runner-pvc

      containers:
        - name: gitlab-runner
          image: 127.0.0.1:5000/gitlab/gitlab-runner:latest
          imagePullPolicy: IfNotPresent

#         command: ["tail", "-f", "/dev/null"]

#         ports:
#           - name: http
#             containerPort: 80

          volumeMounts:
            - name: gitlab-runner-config
              mountPath: /etc/gitlab-runner/config.toml
              subPath: config.toml
#             readOnly: true
#           - name: gitlab-runner-pvc
#             mountPath: /opt/gitlab-runner
#             subPath: 
#             readOnly: true
          
#         resources:
#           requests:
#             cpu: 500m
#             memory: 512Mi
#           limits:
#             cpu: 4
#             memory: 1Gi

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

#     securityContext:
#       runAsUser: 1000
#       runAsGroup: 1000
#       fsGroup: 1000
