apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner
  namespace: default
  labels:
    app: gitlab-runner
spec:
  type: NodePort
  selector:
    app: gitlab-runner
  ports:
    - name: http
      port: 80
      targetPort: 80
#     nodePort: 29880
