apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: registry
  name: registry
  namespace: default
spec:
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: registry
    spec:
      serviceAccountName: registry
#     hostNetwork: true
      terminationGracePeriodSeconds: 30

      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      volumes:
        - name: registry-config
          configMap:
            name: registry-config
            items:
              - key: config.yml
                path: config.yml
        - name: registry-pvc
          persistentVolumeClaim:
            claimName: registry-pvc

      containers:
        - name: registry
          image: library/registry:latest
          imagePullPolicy: IfNotPresent

#         command: [tail, -f, /dev/null]

          ports:
            - name: http
              containerPort: 5000

          volumeMounts:
            - name: registry-config
              mountPath: /etc/distribution/config.yml
              subPath: config.yml
              readOnly: true
            - name: registry-pvc
              mountPath: /var/lib/registry
              subPath: data
#             readOnly: true
          
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 4
              memory: 1Gi

          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

#     securityContext:
#       runAsUser: 1000
#       runAsGroup: 1000
#       fsGroup: 1000
