apiVersion: v1
kind: Service
metadata:
  name: tailscale
  namespace: default
  labels:
    app: tailscale
spec:
  type: NodePort
  selector:
    app: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 80
#     nodePort: 29880
