apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tailscale-storage
  labels:
    app.kubernetes.io/name: tailscale-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
#parameters:
#  type: 
